# Generated by Django 4.1.5 on 2023-01-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("max_floor", models.IntegerField()),
                ("elevator_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elevator_id", models.IntegerField()),
                ("on_floor", models.IntegerField(default=0)),
                ("working", models.BooleanField(default=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Up"), (0, "Halt"), (-1, "Down")], default=0
                    ),
                ),
                (
                    "elevator_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controller.elevatorsystem",
                    ),
                ),
            ],
        ),
    ]
