# Generated by Django 4.1.5 on 2023-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorsystem",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
